### ISSUE TITLE
Endless loop 

### ISSUE THREAD

**Issue by yvesbou** [Everest-Option-Exchange-Team/test-interface#14]
# Problem
The user needs to connect to metamask endlessly.

# Error 

It's not clear to me if this is the cause or just another result of this bug.

```
Error: resolver or addr is not configured for ENS name (argument="name", value="", code=INVALID_ARGUMENT, version=contracts/5.4.1)
    at Logger.makeError (index.js:216:1)
    at Logger.throwError (index.js:226:1)
    at Logger.throwArgumentError (index.js:230:1)
    at index.js:81:1
    at Generator.next (<anonymous>)
    at fulfilled (index.js:13:1)
```

**Comment by yvesbou** [comment]
The infinite loop was a result of wrong usage of useEffect: https://alexsidorenko.com/blog/react-infinite-loop/
